language: c

compiler:
  - gcc

install: 
  - sudo apt-get update || true
  - sudo apt-get install build-essential
  - sudo apt-get install libpcap-dev libexpat-dev libjson0-dev bison flex libtool autoconf automake autogen libuv0.10-dev

script:
  - ./build.sh
  - ./configure
  - make
  - ./src/captagent -h
  - ./src/captagent -v
