matrix:
  include:
    # Plain Agent
    - os: linux
      env:
        - CONFIGURE=""
    # TLS Agent
    - os: linux
      env:
        - CONFIGURE="--enable-tls"      
    # SSL Agent
    - os: linux
      env:
        - CONFIGURE="--enable-ssl"      

language: c

compiler:
  - gcc

install: 
  - sudo -E apt-add-repository -y ppa:linuxjedi/ppa
  - sudo apt-get update || true
  - sudo apt-get install build-essential
  - sudo apt-get install libpcap-dev libexpat-dev libjson0-dev bison flex libtool autoconf automake autogen libuv-dev libgcrypt20 libgcrypt-dev libssl-dev

script:
  - ./build.sh
  - ./configure ${CONFIGURE}
  - make
  - ./src/captagent -h
  - ./src/captagent -v
